# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 482a18104e518b9271a9d1e474a29f209496797b7a8a8beb95d7cd0ba31edfb5007b9e194b009ae4e57a7e8e98bf42ee494bd08ea1c5a1d9ed10e370c067cc2a

test:
  secret_key_base: e9ff915a62c06dab923731be149ab09531e05ed526248c8ebe017de5001487819dc9ea4e77d10a65dcc3012b52fcf55e0b3639dd3be993eb9b594b6ea5e0c56e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
